### ISSUE TITLE
jumanpp 2.0.0-rc3でpyknp/juman/juman.pyのテストに失敗する

### ISSUE THREAD

**Issue by shirayu** [ku-nlp/pyknp#31]
[jumanpp 2.0.0-rc3](https://github.com/ku-nlp/jumanpp/releases/tag/v2.0.0-rc3)で``pyknp/juman/juman.py``のテストに失敗します

```console
$ jumanpp -v
Juman++ Version: 2.0.0-rc3 / Dictionary: 20190731-356e143 / LM: K:20190430-7d143fb L:20181122-b409be68 F:20171214-9d125

$  python3 ./pyknp/juman/juman.py
.F.F.....F
======================================================================
FAIL: test_dquo (__main__.JumanTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pyknp/juman/juman.py", line 148, in test_dquo
    self.assertEqual(''.join(mrph.midasi for mrph in result), test_str)
AssertionError: '”最高”の気分' != '"最高"の気分'
- ”最高”の気分
? ^  ^
+ "最高"の気分
? ^  ^


======================================================================
FAIL: test_eos2 (__main__.JumanTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pyknp/juman/juman.py", line 143, in test_eos2
    self.assertEqual(''.join(mrph.midasi for mrph in result), test_str.replace(" ", "\ "))
AssertionError: 'Canon\u3000EOS\u300080D買った' != 'Canon\\ EOS\\ 80D買った'
- Canon　EOS　80D買った
?      ^   ^
+ Canon\ EOS\ 80D買った
?      ^^   ^^


======================================================================
FAIL: test_whitespace_jumanpp (__main__.JumanTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pyknp/juman/juman.py", line 132, in test_whitespace_jumanpp
    self.assertEqual(''.join(mrph.midasi for mrph in result), test_str.replace(" ", "\ "))
AssertionError: '半角\u3000スペース' != '半角\\ スペース'
- 半角　スペース
?   ^
+ 半角\ スペース
?   ^^


----------------------------------------------------------------------
Ran 10 tests in 0.177s

FAILED (failures=3)
```

**Comment by nobu-g** [comment]
jumanpp 2.0.0 がまだ rc なのでひとまず放置しています
