### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by otariidae** [ku-nlp/pyknp#34]
Minimal reproduce code
```py
knp = KNP()
knp.parse(" ")
```

```
Traceback (most recent call last):
  File "hoge.py", line 79, in <module>
    knp.parse(" ")
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/knp.py", line 70, in parse
    return self.parse_juman_result(juman_str, juman_format)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/knp.py", line 97, in parse_juman_result
    return BList(knp_lines, self.pattern, juman_format)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/blist.py", line 42, in __init__
    self._set_pas(self.juman_format)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/blist.py", line 78, in _set_pas
    tag.pas = Pas(tag.tag_id, self)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/pas.py", line 94, in __init__
    self.__set_args(tag_predicate.features.get("格解析結果"), CaseInfoFormat.CASE)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/pas.py", line 206, in __set_args
    for items in self.__parse_case_analysis_items(analysis_result, case_info_format):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.8/site-packages/pyknp/knp/pas.py", line 184, in __parse_case_analysis_items
    self.cfid = match.group(1) + ':' + match.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
```

KNPの出力
```
$ echo " " | jumanpp | knp -tab
# S-ID:1 KNP:5.0-165d699 DATE:2020/09/11 SCORE:-23.04048
* -1D <文頭><文末><受けNONE><用言:判><体言止><レベル:C><区切:5-5><ID:（文末）><提題受:30><主節><状態述語><正規化代表表記:><主辞代表表記:>
+ -1D <文頭><文末><受けNONE><用言:判><体言止><レベル:C><区切:5-5><ID:（文末）><提題受:30><主節><状態述語><判定詞句><正規化代表表記:><主辞代表表記:><用言代表表記:><CF_NOT_FOUND><節-区切><節-主辞><時制:非過去><格解析結果::判0><標準用言代表表記:>
\ \ \ 特殊 1 空白 6 * 0 * 0 "代表表記: / " <代表表記:></><正規化代表表記:><記英数カ><英記号><記号><文頭><文末><自立><内容語><タグ単位始><文節始><文節主辞><用言表記先頭><用言表記末尾><用言意味表記末尾>
EOS
```

More cases
```
knp.parse("末尾に半角スペースはエラー ") # AttributeError: 'NoneType' object has no attribute 'group'
knp.parse(" 文先頭に半角スペースはエラーなし")
knp.parse("文中に半角スペース エラーなし")
knp.parse(" ！") # AttributeError: 'NoneType' object has no attribute 'group'
knp.parse("！ ！") # AttributeError: 'NoneType' object has no attribute 'group'
```

JUMAN++ 1.02
KNP masterブランチの最新版 https://github.com/ku-nlp/knp/commit/165d699ae8a745860a89925ffd451abb4c93da5a
pyknp 0.4.5
Python 3.8.5
OS Ubuntu 20.04

**Comment by nobu-g** [comment]
Thank you for your report!
I have updated master.
Please try the latest version at master branch.

**Comment by otariidae** [comment]
Tried current HEAD of master 6ba00ea4793c421e517cd5f5488823fd2778d30d and got no error.
Many thanks!
Closing the issue.
