### ISSUE TITLE
照応解析(anaphora)オプションを付けると前の入力を読み続ける

### ISSUE THREAD

**Issue by Ina299** [ku-nlp/pyknp#55]
knp本体の問題な気もしてますがanaphoraオプションを付けると複数文の結果を見ようとするのか前の入力内容をflushしないで延々と関係を見に行くケースがある
そのため同じ単語を多く含む文章郡を何度か投入するとEntity \"%s\" mentiond too many times!で落ちる

**Comment by nobu-g** [comment]
不具合が再現される実例を載せてもらえると助かります．
また，使用している Juman++ / KNP のバージョンなど，環境に関する情報もお願いします．

**Comment by Ina299** [comment]
toy programですが
```
from pyknp import KNP    
import traceback    
knp = KNP(option='-tab -anaphora')     # Default is JUMAN++. If you use JUMAN, use KNP(jumanpp=False)    
ll = ["硫酸を流す","硫酸から流す","硫酸から飛び降りる"]    
for i in range(0,100):  
    for j in ll:  
        try:  
            result = knp.parse(j)  
        except:  
            print(traceback.format_exc())  
            pass  
```
結果は
Entity "硫酸" mentiond too many times!  
Entity "硫酸" mentiond too many times!  

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    result = knp.parse(j)
  File "/Users/xxxx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyknp-0.4-py3.7.egg/pyknp/knp/knp.py", line 79, in parse
    return BList(knp_lines, self.pattern)
  File "/Users/xxxx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyknp-0.4-py3.7.egg/pyknp/knp/blist.py", line 40, in __init__
    self.parse(spec)
  File "/Users/xxxx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyknp-0.4-py3.7.egg/pyknp/knp/blist.py", line 125, in parse
    mrph = Morpheme(string, len(self.mrph_list()), self.newstyle)
  File "/Users/xxxx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyknp-0.4-py3.7.egg/pyknp/juman/morpheme.py", line 66, in __init__
    self._parse_spec(spec.strip("\n"))
  File "/Users/xxxx/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pyknp-0.4-py3.7.egg/pyknp/juman/morpheme.py", line 122, in _parse_spec
    self.hinsi_id = int(parts[4])
ValueError: invalid literal for int() with base 10: 'many'
最初の方にはこのエラー出ないのですが後半になると出るようになります。
JUMAN++ 1.01 
knp 4.19
pyknp 0.4
ただ試しにpyknpのバージョンを0.6に上げたらValueError: invalid literal for int() with base 10: 'many'の方は消えました
これだと依然読んではいるのでおそらく項構造は前のものも読みに行くものの落ちはしないかもです

**Comment by nobu-g** [comment]
バグが再現することを確認しました．
（最新の Juman++ v2-rc3 ， KNP 5.0 ，および pyknp 0.6.2 で試してみましたが同様でした．）

仰る通りこれは KNP の問題かと思います．
[KNP のレポジトリ](https://github.com/ku-nlp/knp) の方に同様の issue を立ててもらえるでしょうか．

取り急ぎの解決策としては，以下のものが考えられます：
- 適当な回数 (例えば 10 回) 解析を行う度に pyknp.KNP インスタンスを作り直す
- KNP インスタンス作成時に `multithreading=True` を指定する (pyknp 0.5.2+)
